# Generated by Django 5.1.4 on 2025-01-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='type',
            field=models.CharField(choices=[('Registration', 'Registration'), ('Absence', 'Absence')], max_length=36),
        ),
    ]
