# Generated by Django 5.1.4 on 2025-01-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='certificate',
            field=models.URLField(blank=True),
        ),
    ]
