# Generated by Django 5.1.4 on 2025-01-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0002_webinar_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='auto_verify',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='webinar',
            name='data_keys',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webinar',
            name='qr',
            field=models.URLField(blank=True),
        ),
    ]
