# Generated by Django 5.1.4 on 2025-01-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0004_rename_serial_number_webinar_serial_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='full_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
