# Generated by Django 5.1.4 on 2025-01-08 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('webinar', '0002_webinar_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('certified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinar.webinar')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='joined_webinars',
            field=models.ManyToManyField(related_name='joined_users', through='authentication.WebinarJoin', to='webinar.webinar'),
        ),
    ]
