# Generated by Django 5.1.4 on 2025-01-09 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_webinarjoin_user_joined_webinars'),
        ('form', '0005_formsubmission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarjoin',
            name='regist_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.form'),
        ),
    ]
