# Generated by Django 5.1.4 on 2025-01-10 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_webinarjoin_regist_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_date', models.DateTimeField(auto_now_add=True)),
                ('webinar_join', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_form', to='authentication.webinarjoin')),
            ],
        ),
    ]
