# Generated by Django 5.1.4 on 2025-01-14 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_absence_date_attendanceform_attendance_date'),
        ('form', '0006_alter_form_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceform',
            name='attendance_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.form'),
        ),
    ]
