# Generated by Django 5.1.4 on 2025-01-16 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_attendanceform_attendance_form'),
        ('form', '0006_alter_form_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarjoin',
            name='form_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.formsubmission'),
        ),
    ]
